version: '2.4'

services:
    tracee:
        container_name: tracee
        pid: host
        privileged: true
        volumes:
            - '/etc/os-release:/etc/os-release-host:ro'
        environment:
            - LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host
            - TRACEE_EBPF_ONLY=1
        logging:
            driver: json-file
        command:
            - --trace container=new
            - --trace event=cap_capable
        image: 'aquasec/tracee:0.7.0'
