version: '2.4'

services:

###### OPC-Server ######
  opc-server:
    image: opc-server:v0.0.1
    build: ./opcua_server_simulator/
    container_name: opc-server
    mem_limit: 200m
    ports:
      - 4841:4841
    networks:
      proxy-redirect:

###### NETWORK DEFINITION ######
networks:
  proxy-redirect:
    name: proxy-redirect
    external: true
